// Code generated by goctl. DO NOT EDIT.
package types

type JwtTokenRequest struct {
}

type JwtTokenResponse struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"` // 建议客户端刷新token的绝对时间
}

type UserFindReq struct {
	UserId int64 `form:"user_id"`
}

type UserFindRes struct {
	UserInfo UserInfo `json:"user_info"`
}

type UserInfo struct {
	UserId int64  `json:"user_id"`
	Name   string `json:"name"`
	Age    int32  `json:"age"`
	Phone  string `json:"phone"`
}

type ExpandReq struct {
	Shorten string `form:"shorten"`
}

type ExpandResp struct {
	Url string `json:"url"`
}

type ShortenReq struct {
	Url string `form:"url"`
}

type ShortenResp struct {
	Shorten string `json:"shorten"`
}
