// Code generated by goctl. DO NOT EDIT!
// Source: userservice.proto

package server

import (
	"context"

	"shorturl/rpc/userservice/internal/logic"
	"shorturl/rpc/userservice/internal/svc"
	user_service "shorturl/rpc/userservice/pb"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) GetUserInfo(ctx context.Context, in *user_service.GetUserInfoReq) (*user_service.GetUserInfoRes, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}
