// Code generated by goctl. DO NOT EDIT!
// Source: userservice.proto

package userservice

import "errors"

var errJsonConvert = errors.New("json convert error")

type (
	GetUserInfoReq struct {
		UserId int64 `json:"user_id,omitempty"`
	}

	GetUserInfoRes struct {
		UserInfo *UserInfo `json:"userInfo,omitempty"`
	}

	UserInfo struct {
		UserId int64  `json:"user_id,omitempty"`
		Name   string `json:"name,omitempty"`
		Age    int32  `json:"age,omitempty"`
	}
)
